#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL (Obstacle Avoidance and vision fusion)
#
# @type Quadrotor Wide
#

. ${R}etc/init.d-posix/airframes/10016_iris




# EKF2: Vision position and heading
param set-default EKF2_AID_MASK 24
param set-default EKF2_HGT_MODE 3
param set-default EKF2_IMU_POS_X 0.1
param set-default EKF2_MAG_TYPE 5
# param set-default EKF2_EV_DELAY 5
